

   CREATE TABLE "users" (
  "id_user" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
  "name_user" varchar(50),
  "email_user" varchar(50) UNIQUE,
  "password_user" varchar(10),
  "status_user" boolean,
  PRIMARY KEY ("id_user")
);

CREATE TABLE IF NOT EXISTS public.users
(
    id_user integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name_user character varying(50) COLLATE pg_catalog."default",
    email_user character varying(50) COLLATE pg_catalog."default",
    password_user character varying(10) COLLATE pg_catalog."default",
    status_user integer NOT NULL DEFAULT 0,
    CONSTRAINT users_pkey PRIMARY KEY (id_user),
    CONSTRAINT users_email_user_key UNIQUE (email_user)
)

